import {
  IconAd,
  IconAi,
  IconAnalyze,
  IconApi,
  IconAtom,
  IconAuth2fa,
  IconBellDollar,
  IconBlocks,
  IconBrain,
  IconBrandAndroid,
  IconBrandApple,
  IconBrandAppleFilled,
  IconBrandAws,
  IconBrandAzure,
  IconBrandDocker,
  IconBrandFirebase,
  IconBrandGoogle,
  IconBrandGoogleAnalytics,
  IconBrandGoogleBigQuery,
  IconBrandGoogleDrive,
  IconBrandGoogleMaps,
  IconBrandGooglePhotos,
  IconBrandOpera,
  IconBrandUbuntu,
  IconBrandWindows,
  IconBugOff,
  IconBuilding,
  IconBuildingCommunity,
  IconCamera,
  IconCell,
  IconCellSignalOff,
  IconChartScatter3d,
  IconCloudBitcoin,
  IconCloudComputing,
  IconCloudDataConnection,
  IconCloudFog,
  IconCloudNetwork,
  IconCloudX,
  IconCode,
  IconCodeAsterisk,
  IconCodeCircle,
  IconCodeDots,
  IconCodeVariable,
  IconCpu,
  IconCpu2,
  IconCube,
  IconCube3dSphere,
  IconDatabase,
  IconDatabaseExport,
  IconDatabaseSmile,
  IconDatabaseStar,
  IconDeviceCctv,
  IconDeviceDesktop,
  IconDeviceHeartMonitor,
  IconDeviceHeartMonitorFilled,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDevicesCog,
  IconDeviceSim,
  IconDeviceTablet,
  IconDeviceTv,
  IconDeviceWatch,
  IconDeviceWatchExclamation,
  IconDots,
  IconEyeBitcoin,
  IconEyeExclamation,
  IconFileDatabase,
  IconFileLike,
  IconFiles,
  IconFlask,
  IconGitBranch,
  IconGraph,
  IconHammer,
  IconHeartRateMonitor,
  IconHttpPatch,
  IconIdBadge,
  IconKey,
  IconLane,
  IconLayersLinked,
  IconLibrary,
  IconLineScan,
  IconLoadBalancer,
  IconLock,
  IconLogs,
  IconMessages,
  IconMoodSick,
  IconNetwork,
  IconPhotoSensor,
  IconPhotoSensor2,
  IconPrinter,
  IconRecordMail,
  IconRouter,
  IconScanPosition,
  IconServer,
  IconServer2,
  IconServerBolt,
  IconServerSpark,
  IconShare3,
  IconShieldBolt,
  IconShieldLock,
  IconSlashes,
  IconStepInto,
  IconSwitch,
  IconTestPipe2Filled,
  IconTimeDuration0,
  IconTimelineEvent,
  IconTree,
  IconTruckDelivery,
  IconUsersGroup,
  IconUvIndex,
  IconView360,
  IconVirusOff,
  IconWall,
  IconWebhook,
} from '@tabler/icons-react'

export const Programming = [
  {
    id: 'compilers',
    label: 'Compilers',
    type: 'programming',
    icon: IconCode,
  },
  {
    id: 'interpreters',
    label: 'Interpreters',
    type: 'programming',
    icon: IconCodeDots,
  },
  {
    id: 'scripting-languages',
    label: 'Scripting Languages',
    type: 'programming',
    icon: IconCodeVariable,
  },
  {
    id: 'libraries',
    label: 'Libraries (React, TensorFlow)',
    type: 'programming',
    icon: IconLibrary,
  },
  {
    id: 'frameworks',
    label: 'Frameworks (Django, Spring)',
    type: 'programming',
    icon: IconCodeAsterisk,
  },
  {
    id: 'middleware',
    label: 'Middleware',
    type: 'programming',
    icon: IconGraph,
  },
  {
    id: 'api-tools',
    label: 'API Development Tools',
    type: 'programming',
    icon: IconApi,
  },
]

export const DistributedSystems = [
  {
    id: 'message-queues',
    label: 'Message Queues (RabbitMQ, Kafka)',
    type: 'distributedSystems',
    icon: IconMessages,
  },
  {
    id: 'distributed-caches',
    label: 'Distributed Caches (Hazelcast)',
    type: 'distributedSystems',
    icon: IconLane,
  },
  {
    id: 'event-sourcing',
    label: 'Event Sourcing Tools',
    type: 'distributedSystems',
    icon: IconTimelineEvent,
  },
  {
    id: 'consensus-algorithms',
    label: 'Consensus Algorithms (Raft, Paxos)',
    type: 'distributedSystems',
    icon: IconUsersGroup,
  },
  {
    id: 'sharding-mechanisms',
    label: 'Sharding Mechanisms',
    type: 'distributedSystems',
    icon: IconShare3,
  },
  {
    id: 'cluster-management',
    label: 'Cluster Management Tools',
    type: 'distributedSystems',
    icon: IconDots,
  },
]

export const DataAnalytics = [
  {
    id: 'etl-tools',
    label: 'ETL Tools (Informatica, Talend)',
    type: 'dataAnalytics',
    icon: IconDatabaseExport,
  },
  {
    id: 'bi-tools',
    label: 'BI Tools (Tableau, Power BI)',
    type: 'dataAnalytics',
    icon: IconBrain,
  },
  {
    id: 'data-visualization',
    label: 'Data Visualization Libraries',
    type: 'dataAnalytics',
    icon: IconChartScatter3d,
  },
  {
    id: 'ml-frameworks',
    label: 'Machine Learning Frameworks',
    type: 'dataAnalytics',
    icon: IconAi,
  },
  {
    id: 'big-data-frameworks',
    label: 'Big Data Frameworks (Hadoop, Spark)',
    type: 'dataAnalytics',
    icon: IconDatabaseSmile,
  },
  {
    id: 'data-pipelines',
    label: 'Data Pipelines',
    type: 'dataAnalytics',
    icon: IconStepInto,
  },
]

export const DevelopmentPractices = [
  {
    id: 'source-code-repositories',
    label: 'Source Code Repositories',
    type: 'developmentPractices',
    icon: IconCodeCircle,
  },
  {
    id: 'code-review-tools',
    label: 'Code Review Tools',
    type: 'developmentPractices',
    icon: IconAnalyze,
  },
  {
    id: 'build-automation-tools',
    label: 'Build Automation Tools',
    type: 'developmentPractices',
    icon: IconHammer,
  },
  {
    id: 'dependency-management-tools',
    label: 'Dependency Management Tools',
    type: 'developmentPractices',
    icon: IconLayersLinked,
  },
]

export const EmergingTechnologies = [
  {
    id: 'quantum-computing-hardware',
    label: 'Quantum Computing Hardware',
    type: 'emergingTechnologies',
    icon: IconAtom,
  },
  {
    id: 'neuromorphic-chips',
    label: 'Neuromorphic Chips',
    type: 'emergingTechnologies',
    icon: IconCell,
  },
  {
    id: 'blockchain-nodes',
    label: 'Blockchain Nodes',
    type: 'emergingTechnologies',
    icon: IconCloudBitcoin,
  },
  {
    id: 'edge-computing-devices',
    label: 'Edge Computing Devices',
    type: 'emergingTechnologies',
    icon: IconCloudComputing,
  },
  {
    id: 'iot-gateways',
    label: 'IoT Gateways',
    type: 'emergingTechnologies',
    icon: IconPhotoSensor,
  },
  {
    id: 'ar-vr-systems',
    label: 'AR/VR Systems',
    type: 'emergingTechnologies',
    icon: IconCube,
  },
]

export const Virtualization = [
  {
    id: 'vms',
    label: 'VMs',
    type: 'virtualization',
    icon: IconCloudDataConnection,
  },
  {
    id: 'docker-containers',
    label: 'Docker Containers',
    type: 'virtualization',
    icon: IconBrandDocker,
  },
  {
    id: 'kubernetes-pods',
    label: 'Kubernetes Pods',
    type: 'virtualization',
    icon: IconCube3dSphere,
  },
  {
    id: 'cloud-clusters',
    label: 'Cloud Clusters',
    type: 'virtualization',
    icon: IconCloudFog,
  },
  {
    id: 'vdi',
    label: 'VDI (Virtual Desktop Infrastructure)',
    type: 'virtualization',
    icon: IconCloudX,
  },
]

export const Miscellaneous = [
  {
    id: 'bios-uefi',
    label: 'BIOS/UEFI',
    type: 'miscellaneous',
    icon: IconDeviceCctv,
  },
  {
    id: 'config-management',
    label: 'Configuration Management Tools (Ansible, Puppet)',
    type: 'miscellaneous',
    icon: IconDevicesCog,
  },
  {
    id: 'logging-systems',
    label: 'Logging Systems',
    type: 'miscellaneous',
    icon: IconLogs,
  },
  {
    id: 'testing-frameworks',
    label: 'Testing Frameworks',
    type: 'miscellaneous',
    icon: IconFlask,
  },
  {
    id: 'emulators',
    label: 'Emulators',
    type: 'miscellaneous',
    icon: IconDeviceSim,
  },
]

export const UMLComponents = {
  emerging: EmergingTechnologies,
  programming: Programming,
  distributed: DistributedSystems,
  data: DataAnalytics,
  development: DevelopmentPractices,
  virtualization: Virtualization,
  miscellaneous: Miscellaneous,
  security: [
    {
      id: 'firewalls',
      label: 'Firewalls',
      type: 'security',
      icon: IconWall,
    },
    {
      id: 'ids',
      label: 'Intrusion Detection Systems (IDS)',
      type: 'security',
      icon: IconEyeExclamation,
    },
    {
      id: 'ips',
      label: 'Intrusion Prevention Systems (IPS)',
      type: 'security',
      icon: IconShieldBolt,
    },
    {
      id: 'encryption',
      label: 'Encryption Modules',
      type: 'security',
      icon: IconCellSignalOff,
    },
    {
      id: 'hsm',
      label: 'HSM (Hardware Security Module)',
      type: 'security',
      icon: IconShieldLock,
    },
    {
      id: 'antivirus',
      label: 'Anti-Virus Software',
      type: 'security',
      icon: IconVirusOff,
    },
    {
      id: 'endpoint-security',
      label: 'Endpoint Security',
      type: 'security',
      icon: IconLineScan,
    },
    {
      id: 'ssl-tls',
      label: 'SSL/TLS Certificates',
      type: 'security',
      icon: IconLock,
    },
    {
      id: 'security-patches',
      label: 'Security Patches',
      type: 'security',
      icon: IconHttpPatch,
    },
    {
      id: 'auth-servers',
      label: 'Authentication Servers',
      type: 'security',
      icon: IconAuth2fa,
    },
    {
      id: 'authz-servers',
      label: 'Authorization Servers',
      type: 'security',
      icon: IconServerSpark,
    },
    {
      id: 'token-management',
      label: 'Token Management Systems',
      type: 'security',
      icon: IconKey,
    },
    {
      id: 'identity-providers',
      label: 'Identity Providers',
      type: 'security',
      icon: IconIdBadge,
    },
  ],
  tools: [
    {
      id: 'ide',
      label: 'IDEs (Visual Studio, IntelliJ IDEA)',
      type: 'softwareAndTools',
      icon: IconDeviceHeartMonitor,
    },
    {
      id: 'vcs',
      label: 'Version Control Systems (Git, SVN)',
      type: 'softwareAndTools',
      icon: IconGitBranch,
    },
    {
      id: 'ci-cd',
      label: 'CI/CD Tools (Jenkins, GitHub Actions)',
      type: 'softwareAndTools',
      icon: IconTruckDelivery,
    },
    {
      id: 'monitoring',
      label: 'Monitoring Tools (Prometheus, Grafana)',
      type: 'softwareAndTools',
      icon: IconHeartRateMonitor,
    },
    {
      id: 'debugging',
      label: 'Debugging Tools (GDB, Valgrind)',
      type: 'softwareAndTools',
      icon: IconBugOff,
    },
    {
      id: 'profilers',
      label: 'Performance Profilers',
      type: 'softwareAndTools',
      icon: IconDeviceHeartMonitorFilled,
    },
    {
      id: 'data-integration',
      label: 'Data Integration Tools',
      type: 'softwareAndTools',
      icon: IconFileDatabase,
    },
    {
      id: 'orchestration',
      label: 'Orchestration Tools',
      type: 'softwareAndTools',
      icon: IconBrandOpera,
    },
  ],
  servers: [
    {
      id: 'server-1',
      label: 'Application Server',
      type: 'server',
      icon: IconServer,
    },
    {
      id: 'server-2',
      label: 'Database Server',
      type: 'server',
      icon: IconServer2,
    },
    {
      id: 'server-3',
      label: 'Web Server',
      type: 'server',
      icon: IconServerBolt,
    },
    { id: 'server-4', label: 'Mail Server', type: 'server', icon: IconServer },
    {
      id: 'server-5',
      label: 'Proxy Server',
      type: 'server',
      icon: IconServer2,
    },
    {
      id: 'server-6',
      label: 'FTP Server',
      type: 'server',
      icon: IconFileLike,
    },
  ],
  os: [
    { id: 'windows', label: 'Windows', type: 'os', icon: IconBrandWindows },
    { id: 'macos', label: 'macOS', type: 'os', icon: IconBrandApple },
    {
      id: 'linux',
      label: 'Linux Distributions (Ubuntu, Fedora, etc.)',
      type: 'os',
      icon: IconBrandUbuntu,
    },
    { id: 'unix', label: 'Unix', type: 'os', icon: IconUvIndex },
    { id: 'android', label: 'Android', type: 'os', icon: IconBrandAndroid },
    { id: 'ios', label: 'iOS', type: 'os', icon: IconBrandAppleFilled },
    {
      id: 'rtos',
      label: 'Real-Time Operating Systems (RTOS)',
      type: 'os',
      icon: IconTimeDuration0,
    },
    {
      id: 'hypervisors',
      label: 'Hypervisors (VMware, Hyper-V)',
      type: 'os',
      icon: IconView360,
    },
    {
      id: 'docker',
      label: 'Docker Containers',
      type: 'os',
      icon: IconBrandDocker,
    },
  ],
  storage: [
    {
      id: 'san',
      label: 'SAN (Storage Area Network)',
      type: 'storage',
      icon: IconFileDatabase,
    },
    {
      id: 'nas',
      label: 'NAS (Network Attached Storage)',
      type: 'storage',
      icon: IconFileDatabase,
    },
    {
      id: 'data-lakes',
      label: 'Data Lakes',
      type: 'storage',
      icon: IconDatabase,
    },
    {
      id: 'cloud-storage',
      label: 'Cloud Storage Services',
      type: 'storage',
      icon: IconDatabase,
    },
    {
      id: 'object-storage',
      label: 'Object Storage',
      type: 'storage',
      icon: IconFileDatabase,
    },
    {
      id: 'block-storage',
      label: 'Block Storage',
      type: 'storage',
      icon: IconFileDatabase,
    },
    {
      id: 'file-systems',
      label: 'File Systems (NTFS, ext4, etc.)',
      type: 'storage',
      icon: IconFileDatabase,
    },
    {
      id: 'backup-devices',
      label: 'Backup Devices',
      type: 'storage',
      icon: IconFileDatabase,
    },
    {
      id: 'tape-drives',
      label: 'Tape Drives',
      type: 'storage',
      icon: IconFileDatabase,
    },
    {
      id: 'relational-databases',
      label: 'Relational Databases (MySQL, PostgreSQL)',
      type: 'database',
      icon: IconDatabase,
    },
    {
      id: 'nosql-databases',
      label: 'NoSQL Databases (MongoDB, Cassandra)',
      type: 'database',
      icon: IconDatabase,
    },
    {
      id: 'in-memory-databases',
      label: 'In-Memory Databases (Redis, Memcached)',
      type: 'database',
      icon: IconDatabase,
    },
    {
      id: 'data-warehouses',
      label: 'Data Warehouses',
      type: 'database',
      icon: IconDatabase,
    },
    {
      id: 'raid-arrays',
      label: 'RAID Arrays',
      type: 'storage',
      icon: IconFileDatabase,
    },
    {
      id: 'cache-systems',
      label: 'Cache Systems',
      type: 'storage',
      icon: IconFileDatabase,
    },
  ],
  clients: [
    {
      id: 'client-1',
      label: 'Desktop Client',
      type: 'client',
      icon: IconDeviceDesktop,
    },
    {
      id: 'client-2',
      label: 'Mobile Client',
      type: 'client',
      icon: IconDeviceMobile,
    },
    {
      id: 'client-3',
      label: 'Tablet Client',
      type: 'client',
      icon: IconDeviceTablet,
    },
    {
      id: 'client-4',
      label: 'Laptop Client',
      type: 'client',
      icon: IconDeviceLaptop,
    },
    {
      id: 'client-5',
      label: 'Smart TV Client',
      type: 'client',
      icon: IconDeviceTv,
    },
    {
      id: 'device-1',
      label: 'Printer',
      type: 'device',
      icon: IconPrinter,
    },
    {
      id: 'device-2',
      label: 'Scanner',
      type: 'device',
      icon: IconScanPosition,
    },
    {
      id: 'device-3',
      label: 'Camera',
      type: 'device',
      icon: IconCamera,
    },
    {
      id: 'device-4',
      label: 'IoT Device',
      type: 'device',
      icon: IconPhotoSensor2,
    },
    {
      id: 'device-5',
      label: 'Smart Watch',
      type: 'device',
      icon: IconDeviceWatch,
    },
  ],
  network: [
    { id: 'router-1', label: 'Router', type: 'network', icon: IconRouter },
    {
      id: 'switch-1',
      label: 'Switch',
      type: 'network',
      icon: IconSwitch,
    },
    { id: 'network-1', label: 'Firewall', type: 'network', icon: IconNetwork },
    {
      id: 'network-2',
      label: 'Load Balancer',
      type: 'network',
      icon: IconLoadBalancer,
    },
    {
      id: 'network-3',
      label: 'Gateway',
      type: 'network',
      icon: IconCloudNetwork,
    },
  ],
  services: [
    {
      id: 'service-1',
      label: 'Web Service',
      type: 'service',
      icon: IconWebhook,
    },
    {
      id: 'service-2',
      label: 'Database Service',
      type: 'service',
      icon: IconDatabaseStar,
    },
    {
      id: 'service-3',
      label: 'Authentication Service',
      type: 'service',
      icon: IconAuth2fa,
    },
    {
      id: 'service-4',
      label: 'Email Service',
      type: 'service',
      icon: IconRecordMail,
    },
    {
      id: 'service-5',
      label: 'File Service',
      type: 'service',
      icon: IconFiles,
    },
  ],
  applications: [
    {
      id: 'app-1',
      label: 'CRM Application',
      type: 'application',
      icon: IconSlashes,
    },
    {
      id: 'app-2',
      label: 'ERP Application',
      type: 'application',
      icon: IconBuildingCommunity,
    },
    {
      id: 'app-3',
      label: 'HR Application',
      type: 'application',
      icon: IconDeviceDesktop,
    },
    {
      id: 'app-4',
      label: 'Finance Application',
      type: 'application',
      icon: IconBellDollar,
    },
    {
      id: 'app-5',
      label: 'Marketing Application',
      type: 'application',
      icon: IconAd,
    },
  ],
  firebase: [
    {
      id: 'firebase-auth',
      label: 'Firebase Auth',
      type: 'firebase',
      icon: IconBrandFirebase,
    },
    {
      id: 'firebase-firestore',
      label: 'Firestore',
      type: 'firebase',
      icon: IconBrandFirebase,
    },
    {
      id: 'firebase-storage',
      label: 'Firebase Storage',
      type: 'firebase',
      icon: IconBrandFirebase,
    },
    {
      id: 'firebase-functions',
      label: 'Cloud Functions',
      type: 'firebase',
      icon: IconBrandFirebase,
    },
    {
      id: 'firebase-messaging',
      label: 'Cloud Messaging',
      type: 'firebase',
      icon: IconBrandFirebase,
    },
  ],
  aws: [
    { id: 'aws-ec2', label: 'EC2', type: 'aws', icon: IconBrandAws },
    { id: 'aws-cognito', label: 'Cognito', type: 'aws', icon: IconBrandAws },
    { id: 'aws-s3', label: 'S3', type: 'aws', icon: IconBrandAws },
    { id: 'aws-rds', label: 'RDS', type: 'aws', icon: IconBrandAws },
    { id: 'aws-lambda', label: 'Lambda', type: 'aws', icon: IconBrandAws },
    {
      id: 'aws-cloudfront',
      label: 'CloudFront',
      type: 'aws',
      icon: IconBrandAws,
    },
  ],
  googleCloud: [
    {
      id: 'gcp-compute',
      label: 'Compute Engine',
      type: 'googleCloud',
      icon: IconBrandGoogle,
    },
    {
      id: 'gcp-storage',
      label: 'Cloud Storage',
      type: 'googleCloud',
      icon: IconBrandGoogle,
    },
    {
      id: 'gcp-sql',
      label: 'Cloud SQL',
      type: 'googleCloud',
      icon: IconBrandGoogleBigQuery,
    },
    {
      id: 'gcp-sql',
      label: 'BigQuery',
      type: 'googleCloud',
      icon: IconBrandGoogleBigQuery,
    },
    {
      id: 'gcp-maps',
      label: 'Maps',
      type: 'googleCloud',
      icon: IconBrandGoogleMaps,
    },
    {
      id: 'gcp-photo',
      label: 'Photo',
      type: 'googleCloud',
      icon: IconBrandGooglePhotos,
    },
    {
      id: 'gcp-drive',
      label: 'Drive',
      type: 'googleCloud',
      icon: IconBrandGoogleDrive,
    },
    {
      id: 'gcp-functions',
      label: 'Cloud Functions',
      type: 'googleCloud',
      icon: IconBrandGoogleAnalytics,
    },
    {
      id: 'gcp-pubsub',
      label: 'Pub/Sub',
      type: 'googleCloud',
      icon: IconCloudNetwork,
    },
    {
      id: 'gcp-4',
      label: 'Google Analytics 4',
      type: 'googleCloud',
      icon: IconBrandGoogleAnalytics,
    },
  ],
  azure: [
    {
      id: 'azure-vm',
      label: 'Virtual Machines',
      type: 'azure',
      icon: IconBrandAzure,
    },
    {
      id: 'azure-blob',
      label: 'Blob Storage',
      type: 'azure',
      icon: IconBrandAzure,
    },
    {
      id: 'azure-sql',
      label: 'SQL Database',
      type: 'azure',
      icon: IconBrandAzure,
    },
    {
      id: 'azure-functions',
      label: 'Azure Functions',
      type: 'azure',
      icon: IconBrandAzure,
    },
    { id: 'azure-cdn', label: 'CDN', type: 'azure', icon: IconBrandAzure },
  ],
  hardware: [
    { id: 'cpu', label: 'CPU', type: 'hardware', icon: IconCpu },
    { id: 'gpu', label: 'GPU', type: 'hardware', icon: IconCpu2 },
    { id: 'ram', label: 'RAM', type: 'hardware', icon: IconCpu2 },
    { id: 'rom', label: 'ROM', type: 'hardware', icon: IconDeviceDesktop },
    { id: 'ssd', label: 'SSD', type: 'hardware', icon: IconMoodSick },
    { id: 'hdd', label: 'HDD', type: 'hardware', icon: IconDeviceDesktop },
    {
      id: 'motherboard',
      label: 'Motherboard',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    { id: 'nic', label: 'NIC', type: 'hardware', icon: IconDeviceDesktop },
    { id: 'psu', label: 'PSU', type: 'hardware', icon: IconDeviceDesktop },
    {
      id: 'heatsink',
      label: 'Heatsink',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    {
      id: 'cooling-fans',
      label: 'Cooling Fans',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    {
      id: 'raid-controller',
      label: 'RAID Controller',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    { id: 'ups', label: 'UPS', type: 'hardware', icon: IconDeviceDesktop },
    { id: 'tpm', label: 'TPM', type: 'hardware', icon: IconDeviceDesktop },
    {
      id: 'pcie-cards',
      label: 'PCIe Cards',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    {
      id: 'usb-ports',
      label: 'USB Ports',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    {
      id: 'serial-ports',
      label: 'Serial Ports',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    {
      id: 'ethernet-ports',
      label: 'Ethernet Ports',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    {
      id: 'thunderbolt-ports',
      label: 'Thunderbolt Ports',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    {
      id: 'hdmi-ports',
      label: 'HDMI Ports',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    {
      id: 'display-connectors',
      label: 'Display Connectors',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    {
      id: 'bios-uefi-chips',
      label: 'BIOS/UEFI Chips',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    {
      id: 'cmos-battery',
      label: 'CMOS Battery',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    { id: 'vram', label: 'VRAM', type: 'hardware', icon: IconDeviceDesktop },
    { id: 'fpgas', label: 'FPGAs', type: 'hardware', icon: IconDeviceDesktop },
    { id: 'asics', label: 'ASICs', type: 'hardware', icon: IconDeviceDesktop },
    {
      id: 'optical-drives',
      label: 'Optical Drives',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    {
      id: 'monitors',
      label: 'Monitors',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    {
      id: 'keyboards',
      label: 'Keyboards',
      type: 'hardware',
      icon: IconDeviceDesktop,
    },
    { id: 'mice', label: 'Mice', type: 'hardware', icon: IconDeviceDesktop },
  ],
}

// arcTypes.ts
export const ArcTypes = {
  synchronous: {
    label: 'Synchronous',
    style: { stroke: 'blue', strokeWidth: 2 },
  },
  asynchronous: {
    label: 'Asynchronous',
    style: { stroke: 'green', strokeDasharray: '5,5', strokeWidth: 2 },
  },
}
